# Generated by Django 5.1.3 on 2024-12-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_departement', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('nombre_etudiant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('classe', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/photo_eleves/')),
                ('nom_pere', models.CharField(max_length=100)),
                ('profession_pere', models.CharField(max_length=100)),
                ('telephone_pere', models.CharField(max_length=15)),
                ('email_pere', models.EmailField(blank=True, max_length=254, null=True)),
                ('nom_mere', models.CharField(max_length=100)),
                ('profession_mere', models.CharField(max_length=100)),
                ('telephone_mere', models.CharField(max_length=15)),
                ('email_mere', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matiere', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('date_entree', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPreschool.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPreschool.niveauclasse'),
        ),
    ]
