# Generated by Django 5.1.3 on 2024-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPreschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('matricule', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignant',
            },
        ),
    ]
