# Generated by Django 5.1.3 on 2024-12-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPreschool', '0002_inscriptionenseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='nom_utilisateur',
        ),
    ]
